disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - object_literal
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last

included:
  - Sources

excluded:
  - Tests/LinuxMain.swift
  - Tests/AppTests/XCTestManifests.swift
  - .build

line_length:
  warning: 120
  error: 160

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60